package OrganClinicPOJOs;

public class Blood {

}

/*
 * TODO GETTER, SETTER, COSNTRUCTOR VARIBALE TYPE
 * WE CAN DO THAT WHEN THE THEY CHOOSE THE BLOOD WECAN DO THAT THEY SELECT THEY BLOOD WITH A SELECTION
 * */
