package OrganClinicPOJOs;

public enum TypeSize {
	CHILD, ADULT
}
//REMEMBER THAT WE WILL NOT USE THIS ENUM
//BECAUSE IS BETTER TO USE STRING AS SQLite DO NOT RECOGNISE ENUM

//THIS WILL HELP TO KNOW THE DIFFERENT OPTIONS